Sources/Starknet/Data/Felt.swift

The `value` can be useful for consumers when making contract calls to access the value, e.g. pulling a balance.

Promote `Felt`'s value to be public

---

Sources/Starknet/Crypto/Keccak.swift
Sources/Starknet/Data/Selector.swift

We need public access to compute the hash of a message to be signed.

Make `keccak` public to allow sign arbitrary messages

---

Sources/CryptoToolkit/CryptoCpp.swift
Sources/CryptoToolkit/CryptoRs.swift
Sources/CryptoToolkit/CryptoToolkitError.swift
Sources/CryptoToolkit/Utils.swift
Sources/Starknet/Crypto/StarknetCurve.swift
Tests/StarknetTests/Crypto/StarknetCurveTests.swift

When a function from crypto-cpp executes successfully, it only uses as much buffer as it requires. However, in case of an error, it uses 1024 byte size buffer. This wasn't handled, and caused bad access errorrs.
Also made pedersen hush function non-throwable.

Fixed memory problem with crypto-cpp buffer.

---

Sources/Starknet/Data/Execution.swift

Made initializer of ExecutionParams public.
Also, after the problem with transaction version for estimateFee is solved, we might consider if it's worth using ExecutionParams struct instead of just nonce and maxFee.

Updated ExectutionParams visibility

---

Sources/Starknet/Providers/StarknetProvider/JsonRpcMethod.swift
Sources/Starknet/Providers/StarknetProvider/JsonRpcParams.swift
Sources/Starknet/Providers/StarknetProvider/StarknetProvider.swift
Sources/Starknet/Providers/StarknetProviderProtocol.swift

[ADD]  Implement starknet_estimateMessageFee method

---

Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Data/ExecutionTests.swift
Tests/StarknetTests/Devnet/DevnetClientTests.swift
Tests/StarknetTests/Providers/ProviderTests.swift
Tests/StarknetTests/Utils/DevnetClient/DevnetClient.swift
Tests/StarknetTests/Utils/DevnetClient/DevnetClientModels.swift

The `xcodebuild docbuild` command is the part of release CI workflow, which currently fails because of this command.
Apparently, the reason is using static values from `DevnetClient`, which fails because `DevnetClient` is **internal**, even though building and testing using XCode istelf works without issue despite that. 
Since we probably want to keep `DevnetClient` and classes it uses **internal**, we could instead use enum `DevnetClientConstants` to hold the constants. We could then:
- Access `DevnetClientConstants` in methods inside `DevnetClient` methods when we need default values for arguments.
- Add `constants` field to easily access constants from `DevnetClientProtocol` from outside without needing to be aware of `DevnetClientConstants`.
Closes #108

Replace static fields with single constants field in DevnetClient

---

.github/workflows/checks.yml
Sources/Starknet/Providers/StarknetProvider/JsonRpcResponse.swift
Sources/Starknet/Providers/StarknetProvider/StarknetProvider.swift
Tests/StarknetTests/Data/JsonRpcResponseTests.swift

Cherry-picked from #124 to support errors with any `data` in RPC 0.5.0-compatible version of starknet.swift 
- Remove `JsonRpcErrorData`
- `JsonRpcError.data` is now of type `String?` instead of `JsonRpcErrorData?`; convert any raw json to `String`

[0.7.4] Support any data in JsonRpcError

---

Sources/Starknet/Accounts/StarknetAccount.swift
Sources/Starknet/Accounts/StarknetAccountProtocol.swift
Sources/Starknet/Data/StarknetChainId.swift
Sources/Starknet/Data/Transaction/TransactionHash.swift
Sources/Starknet/Providers/StarknetProvider/StarknetProvider.swift
Sources/Starknet/Providers/StarknetProviderProtocol.swift
Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Data/ExecutionTests.swift
Tests/StarknetTests/Data/StarknetChainIdTests.swift
Tests/StarknetTests/Providers/ProviderTests.swift

Closes #153
-  `StarknetAccount` constructor now has a mandatory `chainId` argument
- `StarknetAccountProtocol` now has `chainId: StarknetChainId` property

Set chain ID in StarknetAccount initializer

---

Sources/Starknet/Accounts/StarknetAccount.swift
Sources/Starknet/Accounts/StarknetAccountProtocol.swift
Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Data/ExecutionTests.swift
Tests/StarknetTests/Providers/ProviderTests.swift

As part of https://github.com/software-mansion/starknet.swift/pull/151, https://github.com/software-mansion/starknet.swift/pull/154, https://github.com/software-mansion/starknet.swift/pull/155, which have restored the ability to set a specific chain ID during initialization and eliminated the need to fetch it at runtime, it is no longer necessary to define all signing methods as asynchronous.

Change signing methods which are no longer async

---

Sources/Starknet/Data/Transaction/Data/StarknetTransactionVersion.swift
Sources/Starknet/Data/Transaction/Transaction.swift
Sources/Starknet/Data/Transaction/TransactionHash.swift
Sources/Starknet/Data/Transaction/TransactionProtocol.swift
Sources/Starknet/Data/Transaction/TransactionWrapper.swift
Tests/StarknetTests/Data/TransactionTests.swift

-- Support RPC 0.7.0 (#162)
-- Add `execute` methods with custom fee multipliers (#163) 
-- Add transaction version enum (#164)
-- Refactor receipts (#165)
As all the tx versions are enums in the 0.7 spec, use enums instead of raw values in the SDK
Closes
- `version` of `StarknetTransaction` is now of type `StarknetTransactionVersion` instead of `Felt`; This applies to all derived transaction structs

Add transaction version enum

---

Sources/Starknet/Data/Transaction/TransactionReceipt.swift
Sources/Starknet/Data/Transaction/TransactionReceiptProtocol.swift
Sources/Starknet/Data/Transaction/TransactionReceiptWrapper.swift
Tests/StarknetTests/Data/TransactionReceiptTests.swift

-- Support RPC 0.7.0 (#162)
-- Add `execute` methods with custom fee multipliers (#163) 
-- Add transaction version enum (#164)
-- Refactor receipts (#165)
Adjust SDK following changes to tx receipts schemas in RPC 0.7.0.
Merge receipt structs with block info (a.k.a `processed`) and without it (a.k.a `pending`)
-  Remove `StarknetPendingTransactionReceipt`, `StarknetProcessedTransactionReceipt` protocols
- Add optional `blockHash` and `blockNumber` to `StarknetTransactionReceipt` protocol and all derived `Starknet[..]TransactionReceipt` structs
Closes
- Removed `StarknetPendingTransactionReceipt`, `StarknetProcessedTransactionReceipt` protocols
- Renamed all `Starknet[..]TransactionReceipt` protocols to `Starknet[..]TransactionReceiptProtocol`
- Removed all …

Refactor receipts

---

Sources/Starknet/Accounts/StarknetAccount.swift
Sources/Starknet/Accounts/StarknetAccountProtocol.swift
Sources/Starknet/Crypto/FeeCalculation.swift
Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Crypto/FeeEstimateTests.swift

-- Support RPC 0.7.0 (#162)
-- Add `execute` methods with custom fee multipliers (#163) 
-- Add transaction version enum (#164)
-- Refactor receipts (#165)
- Use multipliers instead of overheads in fee calculation utils
- Add `executeV1`, `executeV3` methods in `StarknetAccount` with estimate fee multipliers
- Update docstrings for `executeVX` with `call(s)` as only argument to be in line with the new methods
Closes
- `StarknetFeeEstimate` extension fee calculation utils
- `toResourceBounds()` now takes `amountMultiplier`, `unitPriceMultiplier` instead of `amountOverhead`, `unitPriceOverhead`
- `toMaxFee()` now takes `multiplier` instead of `overhead`

Add `execute` methods with custom fee multipliers

---

.github/workflows/checks.yml
Sources/Starknet/Accounts/StarknetAccount.swift
Sources/Starknet/Accounts/StarknetAccountProtocol.swift
Sources/Starknet/Crypto/FeeCalculation.swift
Sources/Starknet/Data/Responses.swift
Sources/Starknet/Data/Transaction/Data/ExecutionResources.swift
Sources/Starknet/Data/Transaction/Data/StarknetTransactionVersion.swift
Sources/Starknet/Data/Transaction/Transaction.swift
Sources/Starknet/Data/Transaction/TransactionHash.swift
Sources/Starknet/Data/Transaction/TransactionProtocol.swift
Sources/Starknet/Data/Transaction/TransactionReceipt.swift
Sources/Starknet/Data/Transaction/TransactionReceiptProtocol.swift
Sources/Starknet/Data/Transaction/TransactionReceiptWrapper.swift
Sources/Starknet/Data/Transaction/TransactionTrace.swift
Sources/Starknet/Data/Transaction/TransactionWrapper.swift
Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Crypto/FeeEstimateTests.swift
Tests/StarknetTests/Data/TransactionReceiptTests.swift
Tests/StarknetTests/Data/TransactionTests.swift
Tests/StarknetTests/Providers/ProviderTests.swift
Tests/StarknetTests/Utils/DevnetClient/DevnetClient.swift

-- Support RPC 0.7.0 (#162)
-- Add `execute` methods with custom fee multipliers (#163) 
-- Add transaction version enum (#164)
-- Refactor receipts (#165)
- Update `StarknetExecutionResources`; Add `StarknetComputationResources`
- Add `executionResources` to tx traces
- Add `computationResources` to `StarknetFunctionInvocation`
- Fee-related changes
- Add `dataGasConsumed` and `dataGasPrice` to  `StarknetFeeEstimate`
- Update `maxAmount` calculation logic in `toResourceBounds()` 
- Use multipliers instead of overheads in fee calculation utils
- Increase multipliers used in `toResourceBounds()` by default; Use **1.5** multiplier (analogous to **0.5** overhead) 
- Add `executeV1`, `executeV3` methods in `StarknetAccount` with estimate fee multipliers
- Introduce …

Support RPC 0.7.0

---

Sources/Starknet/Data/TypedData/StarknetTypedData.swift
Tests/StarknetTests/Data/TypedDataTests.swift
Tests/StarknetTests/Resources/TypedData/typed_data_rev_1_preset_types_example.json

- #172
- #166
- #167
- #170
- #173
- #174
- #175
- #178
- #179
Support revision 1 preset types in `StarknetTypedData` in line with SNIP-12
Closes

Support preset types in `StarknetTypedData`

---

.github/workflows/build_and_publish_docs.yml

- Bump docs runner: use `macos-14` instead of `macos-12`
- Add `Xcode 15.3` setup, to ensure `swift 5.10` usage
Closes #184

Bump docs runner version

---

Sources/Starknet/Data/TypedData/TypeDeclaration.swift

- Add `TypeDeclarationWrapper.encode()` method to properly encode `types` in `StarknetTypedData`
Closes #196

Fix types encoding in StarknetTypedData

---

Tests/StarknetTests/Crypto/FeeEstimateTests.swift

- Fix wrongly calculated `overallFee` passed while initializing `StarknetFeeEstimate` test cases
Closes

Fix calculated overall fees in `FeeEstimateTests`

---

Sources/Starknet/Data/Responses.swift
Tests/StarknetTests/Crypto/FeeEstimateTests.swift

- Add public `init` for `StarknetFeeEstimate`
- Add public `init` for `StarknetFeeEstimate` with automatic `overallFee` calculation
Closes #197

Add public `init` for `StarknetFeeEstimate`

---

Sources/Starknet/Data/TypedData/StarknetTypedData.swift
Sources/Starknet/Data/TypedData/TypeDeclaration.swift
Tests/StarknetTests/Data/TypedDataTests.swift
Tests/StarknetTests/Resources/TypedData/typed_data_rev_1_timestamp_example.json
Tests/StarknetTests/Utils/StarknetTypedData.swift

Fix encoding of `u128`, `i128` and `timestamp`
**Before**: When typed data was decoded to `StarknetTypedData` and then encoded again to JSON,  `u128`, `i128` and `timestamp` were encoded as hex values
**Now**: They are encoded in line with [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md)
Closes #204, #205, #206

Fix typed data serialization

---

Sources/Starknet/Data/TypedData/StarknetTypedData.swift
Sources/Starknet/Data/TypedData/TypeDeclaration.swift
Tests/StarknetTests/Data/TypedDataTests.swift
Tests/StarknetTests/Resources/TypedData/typed_data_rev_1_timestamp_example.json
Tests/StarknetTests/Utils/StarknetTypedData.swift

Add `hotfix` from `v0.10.2` to `main`
Closes

Merge `v0.10.2` into `main`

---

Sources/Starknet/Data/TypedData/StarknetTypedData.swift
Tests/StarknetTests/Data/TypedDataTests.swift

`version` in `Domain` is now encoded as string, instead of number
Closes #227

Fix encoding `version`  in typed data `Domain`

---

Sources/Starknet/Data/TypedData/StarknetTypedData.swift
Tests/StarknetTests/Data/TypedDataTests.swift

Reverts software-mansion/starknet.swift#228

Revert "Fix encoding `version`  in typed data `Domain`"

---

Tests/StarknetTests/Accounts/AccountTest.swift
Tests/StarknetTests/Data/ExecutionTests.swift
Tests/StarknetTests/Devnet/DevnetClientTests.swift
Tests/StarknetTests/Providers/ProviderTests.swift
Tests/StarknetTests/Utils/DevnetClient/DevnetClient.swift
Tests/StarknetTests/Utils/DevnetClient/DevnetClientModels.swift

This PR removes usage of `UInt128` which results in removal macOS 15.0 requirement in our tests
Closes

Remove usage of `UInt128` from `prefundAccount`

---

Package.resolved
Package.swift
Sources/Starknet/Data/ContractAddressCalculator.swift

- Update CryptoSwift from 1.5.1 to 1.9.0
The CryptoSwift 1.9.0 update includes the bytes -> byteArray property rename to avoid conflicts with Swift 6.2's new bytes: RawSpan property ([SE-0456](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://forums.swift.org/t/se-0456-add-span-providing-properties-to-standard-library-types/77233&ved=2ahUKEwj9l5OKldaOAxXLBdsEHWtvJv4QFnoECBQQAQ&usg=AOvVaw3LNKb5YSa_XAScxJ2BuGwP)).

Update dependencies for Swift 6.2 compatibility
